---
title: "Untitled"
author: "Dominique CHAPELON"
date: "06/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ssh)

# ATTENTION il faut ici une clé privée au format PEM
#chemin <- "C:/99_INSTALLATION/DOCKER/test_3/private_PEM"
chemin <- "C:/Users/Myrtille/Documents/R/SSH/R_SSH/private_PEM"

session <- ssh_connect("test@192.168.1.17",keyfile=chemin)
print(session)
ssh_disconnect(session)
```
```{r}
#ssh_key_info()

# :\PuTTY\plink.exe test@192.168.1.17 -i "C:/Users/Myrtille/Documents/R/SSH/R_SSH/private.ppk" Rscript -e rnorm(100) 
```

```{r}
# ATTENTION il faut ici une clé privée au format PPK
#chemin <- "C:/99_INSTALLATION/DOCKER/test_3/private.ppk"
chemin <- "C:/Users/Myrtille/Documents/R/SSH/R_SSH/private.ppk"
primary <- '192.168.1.17'

machineAddresses <- list(
  list(host=primary,user='test',ncore=2)
)

spec <- lapply(machineAddresses,
               function(machine) {
                 rep(list(list(host=machine$host,
                               user=machine$user)),
                     machine$ncore)
               })
spec <- unlist(spec,recursive=FALSE)

#----------------------------------------------------------------------------------------------
# RESULTAT : KO
# parallelCluster <- parallel::makeCluster(type='PSOCK',
#                                          master=primary,
#                                          spec=spec,
#                                          rshcmd = c("C:/PuTTY/plink.exe", "-ssh"),
#                                          rshopts = c("-i", chemin)
#                                          )


# https://github.com/HenrikBengtsson/future/issues/136
#----------------------------------------------------------------------------------------------
# Avec la librairie future V1
# RESULTAT : OK
library("future")
workers <- c(primary, primary)
parallelCluster <-  makeClusterPSOCK(workers,
                                     user = "test",
                                     rshcmd = c("C:/PuTTY/plink.exe", "-ssh"),
                                     rshopts = c("-i", chemin),
                                     homogeneous = FALSE,
                                     verbose=TRUE
                                     )
parallelCluster <- autoStopCluster(parallelCluster)
print(parallelCluster)
```

```{r}

```



```{r}
# Fermeture custer avec le garbage collector
rm(list = "parallelCluster")
gc()
```

